=== andeliero/Tecweb/data/XMLS/Amministratori.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema" targetNamespace = "http://www.musicbreak.com/admin" xmlns = "http://www.musicbreak.com/admin" elementFormDefault = "qualified">
    <xsd:element name = "amministratori" type="TAmministratori">
        <xsd:unique name="unique-username">
            <xsd:selector xpath="admin"/>
            <xsd:field xpath="username"/>
        </xsd:unique>
    </xsd:element>
	
    <xsd:complexType name = "TAmministratori">
        <xsd:sequence>
            <xsd:element name="admin" type = "TAdmin" maxOccurs = "unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
        
    <xsd:complexType name="TAdmin">
        <xsd:sequence>
            <xsd:element name="username" type="TUsername"/>
            <xsd:element name="password" type="TPassword"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" />
    </xsd:complexType>
        
          
    <xsd:simpleType name="TUsername">
        <xsd:restriction base="xsd:string">
            <xsd:whiteSpace value="collapse"/>
            <xsd:pattern value="[A-Za-z0-9_]{5}[A-Za-z0-9_]*" />
        </xsd:restriction>
    </xsd:simpleType>
        
        
    <xsd:simpleType name="TPassword">
        <xsd:restriction base="xsd:string">
            <xsd:whiteSpace value="collapse"/>
            <xsd:pattern value="[A-Za-z0-9_]{8}[A-Za-z0-9_]*" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== andeliero/Tecweb/data/XML/Amministratori.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
La Password andrÃ  modificata con un algoritmo di criptaggio, intanto la inserisco in chiaro
-->
<amministratori><!-- xmlns="http://www.musicbreak.com" 
            xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
            xs:schemaLocation="http://www.musicbreak.com/data/XML/XMLS Amministratori.xsd">-->
    <admin id="0">
        <username>baronerampante</username>
        <password>malpelo</password>
    </admin>
    <admin id="1">
        <username>tecnoboy</username>
        <password>tunztunz789</password>
    </admin>
    <admin id="2">
        <username>getlucky</username>
        <password>daftpunk90</password>
    </admin>
    <admin id="3">
        <username>bandegialla</username>
        <password>yellow1212</password>
    </admin>
    <admin id="4">
        <username>optimusprime</username>
        <password>lego4ever</password>
    </admin>
    <admin id="5">
        <username>alessandro92</username>
        <password>alexthegr8</password>
    </admin>
</amministratori>
