=== andeliero/Tecweb/data/XMLS/DBsite.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<!--
Creo un unico file xml perché ho la necesssità di mantenere vincoli di integrità
referenziale tra le varie strutture

Ora assumiamo la corretteza per costruzione da script perl, questo per alleggerire 
il sistema ed evitare inutili rallentamenti.
-->

<xsd:schema 
    xmlns:xsd = "http://www.w3.org/2001/XMLSchema" 
    targetNamespace = "http://www.musicbreak.com" 
    xmlns = "http://www.musicbreak.com" 
    elementFormDefault = "qualified"
>
    
    <xsd:element name="root" type="Troot"/>
    
    <xsd:complexType name="Troot">
        <xsd:sequence>
            <xsd:element name="tags" type="Ttags" maxOccurs="1"/>
            <xsd:element name="gallerie" type="TGallerie" maxOccurs="1"/>
            <xsd:element name="editori" type="TEditori" maxOccurs="1"/>
            <xsd:element name="posts" type="TPosts" />
        </xsd:sequence>
    </xsd:complexType>
    
    
    <!-- Tags Definition BEGIN -->
    
     
	
    <xsd:complexType name="Ttags">
        <xsd:sequence>
            <xsd:element name="tag" type="Ttag" maxOccurs = "unbounded" />
        </xsd:sequence>
    </xsd:complexType>
        
    <xsd:complexType name="Ttag">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="id" type="xsd:positiveInteger" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
     
    <!-- Gallerie Definition BEGIN -->
    
    <xsd:complexType name="TGallerie">
        <xsd:sequence>
            <xsd:element name="galleria" type="TGalleria" maxOccurs = "unbounded" />
        </xsd:sequence>
    </xsd:complexType>
        
    <xsd:complexType name="TGalleria">
        <xsd:sequence>
            <xsd:element name="foto" type="TFoto" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" />
    </xsd:complexType>
 
    <xsd:complexType name="TFoto">
        <xsd:sequence>
            <xsd:element name="titolo" type="xsd:string" maxOccurs="1" />
            <xsd:element name="srcPath" type="xsd:string" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- Gallerie Definition END -->
    
    <!-- Editori Definition BEGIN -->

    <xsd:complexType name = "TEditori">
        <xsd:sequence>
            <xsd:element name="editore" type = "TEditore" maxOccurs = "unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
        
    <xsd:complexType name="TEditore">
        <xsd:sequence>
            <xsd:element name="nome" type="TNomeCognome"/>
            <xsd:element name="cognome" type="TNomeCognome"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" />
    </xsd:complexType>
        
    <xsd:simpleType name="TNomeCognome">
        <xsd:restriction base="xsd:string">
            <xsd:whiteSpace value="collapse"/>
            <xsd:pattern value="[A-Za-z]+" />
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Editori Definition END -->
    
    <!-- Amministratori Definition BEGIN -->
    
    <xsd:complexType name = "TAmministratori">
        <xsd:sequence>
            <xsd:element name="admin" type = "TAdmin" maxOccurs = "unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
        
    <xsd:complexType name="TAdmin">
        <xsd:sequence>
            <xsd:element name="username" type="TUsername"/>
            <xsd:element name="password" type="TPassword"/>
        </xsd:sequence>
    </xsd:complexType>
        
          
    <xsd:simpleType name="TUsername">
        <xsd:restriction base="xsd:string">
            <xsd:whiteSpace value="collapse"/>
            <xsd:pattern value="[A-Za-z0-9_]{5}[A-Za-z0-9_]*" />
        </xsd:restriction>
    </xsd:simpleType>
        
        
    <xsd:simpleType name="TPassword">
        <xsd:restriction base="xsd:string">
            <xsd:whiteSpace value="collapse"/>
            <xsd:pattern value="[A-Za-z0-9_]{8}[A-Za-z0-9_]*" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Aministratori Definition END -->

   
   
    <xsd:complexType name="TPosts">
        <xsd:sequence>
            <xsd:element name="eventi" type="TEventi" maxOccurs = "1" />
            <xsd:element name="recensioni" type="TRecensioni" maxOccurs = "1" />
            <xsd:element name="interviste" type="Tinterviste" maxOccurs = "1" />
            <xsd:element name="news" type="TNews" maxOccurs = "1" />
        </xsd:sequence>
    </xsd:complexType>

    <!--
    *******************************************************************************
    ***********************      Tipo Comune      *********************************
    *******************************************************************************
    *******************************************************************************
    -->
    <xsd:complexType name="Tcommon">
        <xsd:sequence>
            <xsd:element name="titolo" type="xsd:string" />
            <xsd:element name="foto" type="Tfoto" />
            <xsd:element name="excerpt" type="Ttesto" />
            <xsd:element name="descrizione" type="Ttesto" />
            <xsd:element name="idautore" type="xsd:positiveInteger" />
            <xsd:element name="data" type="xsd:date" />
            <xsd:element name="tag" type="xsd:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>


    <!--
    *******************************************************************************
    **************************      EVENTI      ***********************************
    *******************************************************************************
    *******************************************************************************
    -->


    <xsd:complexType name="TEventi">
        <xsd:sequence>
            <xsd:element name="evento" type="TEvento" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="TEvento">
        <xsd:complexContent>
            <xsd:extension base="Tcommon">
                <xsd:sequence>
                    <xsd:element name="dataEvento" type="xsd:date"/>
                    <xsd:element name="NumGiorni" type="xsd:positiveInteger" minOccurs="0"/>
                    <xsd:element name="luogo" type="xsd:string"/>
                    <xsd:element name="oraInizio" type="Ttime"/>
                    <xsd:element name="oraFine" type="Ttime"/>
                    <xsd:element name="indirizzo" type="xsd:string"/>
                    <xsd:element name="prezzo" type="Tprezzo"/>
                    <xsd:element name="email" type="Temail"/>
                    <xsd:element name="telefono" type="Ttel"/>
                </xsd:sequence>
                <xsd:attribute name="id" type="TidEvento" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:simpleType name="Ttime">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{2}:[0-9]{2}"/>
            <xsd:whiteSpace value="collapse"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Tfoto">
        <xsd:sequence>
            <xsd:element name="src" type="Tsrc"/>
            <xsd:element name="alt" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    
    
    <xsd:simpleType name="Tsrc">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value=".*\.(jpg|jpeg|png|bmp|gif)"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Temail">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Ttel">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{1,}\s([0-9])+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Tprezzo">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="€[0-9]+\.[0-9]{2}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Ttesto" mixed="true">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="span" type="Tspan" />
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="Tspan">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="xsd:string" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="TidEvento">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="e[1-9][0-9]*" />
        </xsd:restriction>
    </xsd:simpleType>

    <!--
    *******************************************************************************
    **************************      RECENSIONI      *******************************
    *******************************************************************************
    *******************************************************************************
    -->


    <xsd:complexType name="TRecensioni">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="recensione" type="TRecensione"  />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TRecensione">
        <xsd:complexContent>
            <xsd:extension base="Tcommon">
                <xsd:attribute name="id" type="TidRecensione" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:simpleType name="TidRecensione">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="r[1-9][0-9]*" />
        </xsd:restriction>
    </xsd:simpleType>

    <!--
    *******************************************************************************
    **************************      INTERVISTE      *******************************
    *******************************************************************************
    *******************************************************************************
    -->

    <xsd:complexType name="Tinterviste">
        <xsd:sequence maxOccurs="unbounded" >
            <xsd:element name="intervista" type="Tintervista"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Tintervista">
        <xsd:complexContent>
            <xsd:extension base="Tcommon">
                <xsd:sequence>
                    <xsd:element name="intervistato" type="xsd:string" />
                    <xsd:element name="galleria" type="xsd:positiveInteger" />
                </xsd:sequence>
                <xsd:attribute name="id" type="TidIntervista" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:simpleType name="TidIntervista">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="i[1-9][0-9]*" />
        </xsd:restriction>
    </xsd:simpleType>

    <!--
    *******************************************************************************
    **************************      NEWS      *************************************
    *******************************************************************************
    *******************************************************************************
    -->

    <xsd:complexType name="TNews">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="item" type="Titem"  />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Titem">
        <xsd:complexContent>
            <xsd:extension base="Tcommon">
                <xsd:attribute name="id" type="TidNews" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:simpleType name="TidNews">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="n[1-9][0-9]*" />
        </xsd:restriction>
    </xsd:simpleType>

   
        
    
        
</xsd:schema>

=== andeliero/Tecweb/data/XML/DBsite.xml
<?xml version="1.0" encoding="UTF-8"?>
<root><!-- xmlns="http://www.musicbreak.com" 
      xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
      xs:schemaLocation="http://www.musicbreak.com/data/XML/XMLS DBsite.xsd">-->
    <!-- sezione tags -->
    <tags>
        <tag id="0">pop</tag>
        <tag id="1">dance</tag>
        <tag id="2">rock</tag>
        <tag id="3">reaggae</tag>
        <tag id="4">classica</tag>
        <tag id="5">raphiphop</tag>
        <tag id="6">digitalaudio</tag>
	<tag id="7">sanremo2014</tag>
	<tag id="8">metallica</tag>
	<tag id="9">brucespringsteen</tag>
	<tag id="10">jazz</tag>
	<tag id="11">ska</tag>
	<tag id="12">soul</tag>
	<tag id="13">sherwood</tag>
	<tag id="14">tool</tag>
	<tag id="15">alternativemetal</tag>
	<tag id="16">francescorenga</tag>
	<tag id="17">bbking</tag>
	<tag id="18">bambini</tag>
	<tag id="19">cartoni</tag>
	<tag id="20">zoo105</tag>
	<tag id="21">99posse</tag>
	<tag id="22">rollingstones</tag>
	<tag id="23">pearljam</tag>
	<tag id="24">eddievedder</tag>
	<tag id="25">metalcore</tag>
	<tag id="26">metal</tag>
	<tag id="27">trivium</tag>
	<tag id="28">muse</tag>
	<tag id="29">singolo</tag>
    <tag id="30">caparezza</tag><tag id="31">ligabue</tag><tag id="32"> mondovisione</tag><tag id="33">moda'</tag><tag id="34"> pop</tag><tag id="35">thevoice</tag><tag id="36">electrovenice</tag><tag id="37"> elettronica</tag><tag id="38">emma marrone</tag><tag id="39"> rock</tag></tags>

    <!-- GALLERIE -->
    
    <gallerie>
        <galleria id="0">
            <foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi0.jpg</srcPath>
            </foto>
            <foto>
                <titolo>noemiuno</titolo>
                <srcPath>/img/interviste/gallery/noemi1.jpg</srcPath>
            </foto>
            <foto>
                <titolo>noemidue</titolo>
                <srcPath>/img/interviste/gallery/noemi2.jpg</srcPath>
            </foto>
            <foto>
                <titolo>noemitre</titolo>
                <srcPath>/img/interviste/gallery/noemi3.jpg</srcPath>
            </foto>
            <foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi4.jpg</srcPath>
            </foto>
	       <foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi5.jpg</srcPath>
            </foto>
            <foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi6.jpg</srcPath>
            </foto>
			<foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi7.jpg</srcPath>
            </foto>
	        <foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi8.jpg</srcPath>
            </foto>
            <foto>
                <titolo>noemiquattro</titolo>
                <srcPath>/img/interviste/gallery/noemi9.jpg</srcPath>
            </foto>
        </galleria>
	<galleria id="1">
	  <foto><titolo>nome-della-foto 400x600renga.jpg</titolo><srcPath>/img/interviste/gallery/400x600renga.jpg</srcPath></foto>
	  <foto><titolo>nome-della-foto FR_TEMPOREALE_cover.jpg</titolo><srcPath>/img/interviste/gallery/FR_TEMPOREALE_cover.jpg</srcPath></foto>
	  <foto><titolo>nome-della-foto-Francesco-Renga.jpg</titolo><srcPath>/img/interviste/gallery/Francesco-Renga.jpg</srcPath></foto>
	</galleria>
	<galleria id="2">
	  <foto><titolo>nome-della-foto-ZOO_105_New.jpg</titolo><srcPath>/img/interviste/gallery/ZOO_105_New.jpg</srcPath></foto>
	  <foto><titolo>nome-della-foto-top_zoo.jpg</titolo><srcPath>/img/interviste/gallery/top_zoo.jpg</srcPath></foto>
	  <foto><titolo>nome-della-foto-10_Lo_ZOO_105_Upim_POP.jpg</titolo><srcPath>/img/interviste/gallery/10_Lo_ZOO_105_Upim_POP.jpg</srcPath></foto>
	  </galleria>
	<galleria id="3">
	  <foto><titolo>nome-della-foto-eddie-vedder.jpg</titolo><srcPath>/img/interviste/gallery/eddievedder.jpg</srcPath></foto>
	  <foto><titolo>nome-della-foto-Eddie-Vedder.jpg</titolo><srcPath>/img/interviste/gallery/Eddie-Vedder.jpg</srcPath></foto>
	  <foto><titolo>nome-della-foto-pearl-jam-performing-live-in-concert-at-the-o2-arena-04.jpg</titolo><srcPath>/img/interviste/gallery/pearl-jam-performing-live-in-concert-at-the-o2-arena-04.jpg</srcPath></foto>
	  </galleria>
	<galleria id="4"><foto><titolo>Foto galleria numero 0</titolo><srcPath>/img/interviste/gallery/photogalleria-4-0.jpg</srcPath></foto><foto><titolo>Foto galleria numero 1</titolo><srcPath>/img/interviste/gallery/photogalleria-4-1.jpg</srcPath></foto><foto><titolo>Foto galleria numero 2</titolo><srcPath>/img/interviste/gallery/photogalleria-4-2.jpg</srcPath></foto></galleria><galleria id="5"><foto><titolo>Foto galleria numero 0</titolo><srcPath>/img/interviste/gallery/photogalleria-5-0.jpg</srcPath></foto><foto><titolo>Foto galleria numero 1</titolo><srcPath>/img/interviste/gallery/photogalleria-5-1.jpg</srcPath></foto><foto><titolo>Foto galleria numero 2</titolo><srcPath>/img/interviste/gallery/photogalleria-5-2.jpg</srcPath></foto><foto><titolo>Foto galleria numero 3</titolo><srcPath>/img/interviste/gallery/photogalleria-5-3.jpg</srcPath></foto><foto><titolo>Foto galleria numero 4</titolo><srcPath>/img/interviste/gallery/photogalleria-5-4.jpg</srcPath></foto><foto><titolo>Foto galleria numero 5</titolo><srcPath>/img/interviste/gallery/photogalleria-5-5.jpg</srcPath></foto></galleria><galleria id="6"><foto><titolo>Foto galleria numero 0</titolo><srcPath>/img/interviste/gallery/photogalleria-6-0.jpg</srcPath></foto><foto><titolo>Foto galleria numero 1</titolo><srcPath>/img/interviste/gallery/photogalleria-6-1.jpg</srcPath></foto></galleria><galleria id="7"><foto><titolo>Foto galleria numero 0</titolo><srcPath>/img/interviste/gallery/photogalleria-7-0.jpg</srcPath></foto><foto><titolo>Foto galleria numero 1</titolo><srcPath>/img/interviste/gallery/photogalleria-7-1.jpg</srcPath></foto></galleria></gallerie>
    
    <!-- EDITORI -->
    <editori>
        <editore id="0">
            <nome>Mario</nome>
            <cognome>Rossi</cognome>
        </editore>
        <editore id="1">
            <nome>Fabio</nome>
            <cognome>Ros</cognome>
        </editore>
        <editore id="2">
            <nome>Luca</nome>
            <cognome>Bonaldo</cognome>
        </editore>
        <editore id="3">
            <nome>Antonio</nome>
            <cognome>Banderas</cognome>
        </editore>
        <editore id="4">
            <nome>Gianni</nome>
            <cognome>Ottimista</cognome>
        </editore>
        <editore id="5">
            <nome>Alessandro</nome>
            <cognome>Mangio</cognome>
        </editore>
    </editori>

    <posts>
    <!-- EVENTI -->
    <eventi>
        <evento id="e0">
            <titolo>Sixty party</titolo>
            <foto>
                <src>/img/eventi/sixtyparty.jpg</src>
                <alt>descrizione-della-foto</alt>
            </foto>
            <excerpt>Lorem ipsum dolor sit amet, consectetur <span lang="en">adipiscing elit</span>. Sed nec purus tempor, semper elit sit amet, congue massa. Nullam luctus sit amet nibh eget dapibus.</excerpt>
            <descrizione>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec purus tempor, semper elit sit amet, congue massa. Nullam luctus sit amet nibh eget dapibus. Nullam massa magna, vestibulum vel bibendum sodales, facilisis sed dui. Duis suscipit velit vestibulum diam eleifend pretium. Aliquam iaculis orci vitae purus gravida, at suscipit ante adipiscing. Nulla sit amet gravida massa. Aenean pharetra diam orci, in dapibus tortor elementum eu. Aenean quam tortor, venenatis ac lacinia ac, aliquam vel turpis. Sed libero quam, tempus sed orci sed, feugiat egestas lacus. Integer aliquam quam mi, ut aliquam felis rutrum ut. Donec accumsan viverra tortor, et gravida felis dictum non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ante justo, sollicitudin ac nunc at, lacinia sagittis mi. Etiam adipiscing dolor id nisl dictum, sit amet facilisis nisi congue. Quisque eget massa ut augue suscipit rhoncus at vitae odio.
            </descrizione>
            <idautore>1</idautore>
            <data>2014-02-04</data>
	    <tag>1</tag>
            <dataEvento>2014-04-08</dataEvento>
            <luogo>Roma</luogo>
            <oraInizio>22:00</oraInizio>
            <oraFine>02:00</oraFine>
            <indirizzo>via IV Novembre, 4 00100 Roma</indirizzo>
            <prezzo>€11.00</prezzo>
            <email>info@sixtyparty.com</email>
            <telefono>0039 333445566</telefono>
        </evento>	
	<evento id="e2">
	    <titolo>Sherwood Festival 2014</titolo>
	    <foto>
		<src>/img/eventi/sherwood-festival-14.jpg</src>
		<alt>Logo-Sherwood-Festival</alt>
	    </foto>
	    <excerpt>Annunciate ufficialmente le date dell’edizione 2014 di SHERWOOD FESTIVAL, la storica rassegna indipendente padovana che si tiene, ormai da decenni, nel parcheggio Nord dello Stadio Euganeo di Padova.</excerpt>
	    <descrizione>Annunciate ufficialmente le date dell’edizione 2014 di SHERWOOD FESTIVAL, la storica rassegna indipendente padovana che si tiene, ormai da decenni, nel parcheggio Nord dello Stadio Euganeo di Padova. Oltre un mese di musica – con i tantissimi concerti del main e del second stage – e un fitto calendario di appuntamenti culturali e di “festival nel festival” che, dall’11 Giugno al 19 Luglio (dieci giorni in più rispetto ai trenta delle scorse edizioni), trasformeranno un parcheggio in uno spazio sociale vivo e pulsante. Un festival sociale e culturale, un appuntamento a larga e sentita partecipazione, un luogo di incontro e di libertà, attraversato ogni sera da migliaia di persone.</descrizione>
	    <idautore>3</idautore>
	    <data>2014-04-16</data>
	    <tag>13</tag>
	    <dataEvento>2014-06-11</dataEvento>
